//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public short ROLEID { get; set; }
        public string ROLEDESCRIPTION { get; set; }
        public string ROLETYPE { get; set; }
        public Nullable<System.DateTime> CRATEDDATE { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATE { get; set; }
    }
}
