//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkItem()
        {
            this.WorkItemHistories = new HashSet<WorkItemHistory>();
        }
    
        public int Id { get; set; }
        public int ClaimId { get; set; }
        public string WorkItemType { get; set; }
        public int WorkItemStatus { get; set; }
        public string AssignedTo { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual Claim Claim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkItemHistory> WorkItemHistories { get; set; }
    }
}
