//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItemHistory
    {
        public int Id { get; set; }
        public int WorkItemId { get; set; }
        public string WorkItemStatus { get; set; }
        public string AssignedTo { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual WorkItem WorkItem { get; set; }
    }
}
